### PR TITLE
Improved vcom regex parsing, added support for vlog linting

### PR DESCRIPTION
**Pull request by vengin**
- Added support for vlog compiler linting
- Improved vcom regex parsing, to derive column position from double quoted text via 'near' field
- Added UnitTests to verify vcom/vlog regex parsing
- Updated readme

### CODE REVIEW

**Comment by jevogel** [comment]
This looks like a great improvement, thanks!
Can you edit `messages.json` to add the message for the new version?
Do you think this plugin should be renamed to reflect the additional functionality?

**Comment by vengin** [comment]
Didn't know about the `messages.json` file. Updated it without increasing the version (moved tag).

Regarding renaming the plugin - totally agree with that (although I don't know, whether it can cause any incompatibility issues). Initially I was thinking about creating a separate plugin named something like SublimeLinter-modelsim (just to avoid this vcom naming confusion), but decided to pull changes into this project.

**Comment by vengin** [comment]
Sorry about the typos, fixed it (also slightly modified README.md). I am a complete newbie to sublimetext packages development. At least for the python code itself (which I don't really know) you can run it and see if it works. But I don't know, if there are any ways of validating/testing the entire package for any issues.

**Comment by jevogel** [comment]
No problem, this is my first one of these packages as well. I'll go ahead and merge.

**Pull request merged**
